version: "3.1"
services:
    frontend:
        build:
            context: .
            target: 'develop-stage'
        ports:
            - '8080:8080'
        volumes:
            - './frontend:/app'
        command: /bin/sh -c "npm run serve"